#!/bin/sh

if [ -n "$1" ]; then
    DIR=$1
else
    DIR=$HOME
fi

rm $DIR/.bashrc
rm $DIR/.bash_profile

ln -s `pwd`/.bashrc $DIR/.bashrc
ln -s `pwd`/.bashrc.d $DIR/.bashrc.d
ln -s `pwd`/.bash_profile $DIR/.bash_profile
